import { multiple, short, single } from './quiz-types';

export const coverageChoice = [
  single('W1-X01', 1, 'DBMS benefits', 'Compared with separate flat files, which DBMS feature most directly reduces inconsistent copies of the same fact?', 2, [
    'Larger monitor resolution',
    'Longer attribute names',
    'Centralised control of shared data and constraints',
    'Manual duplication across applications',
  ]),
  single('W1-X02', 1, 'Client-server', 'In a client-server database system, which component normally executes requests and manages the shared database?', 1, [
    'The presentation document',
    'The DBMS running on the database server',
    'Every client spreadsheet independently',
    'The network cable itself',
  ]),
  single('W1-X03', 1, 'Relational constraints', 'Which rule is an example of a database integrity constraint?', 3, [
    'Display the enrolment page with a blue heading.',
    'Print a weekly management report.',
    'Sort students alphabetically for one query.',
    'StudentType must be either PG or UG.',
  ]),
  single('W1-X04', 1, 'Table structure', 'Which operation changes the structure of an existing table without deleting it?', 0, [
    'ALTER',
    'SELECT',
    'INSERT',
    'GRANT',
  ]),
  single('W1-X05', 1, 'Table structure', 'Which operation removes an entire table definition and its stored rows?', 2, [
    'DELETE one row',
    'RENAME',
    'DROP',
    'UPDATE',
  ]),
  single('W1-X06', 1, 'Database lifecycle', 'Which lifecycle activity defines the scope, users, major user views and system boundaries?', 1, [
    'Operational maintenance',
    'Systems definition',
    'Data loading',
    'Query execution',
  ]),
  single('W1-X07', 1, 'Database lifecycle', 'Which activity transfers data from an old system into the new database?', 3, [
    'Conceptual modelling',
    'Systems definition',
    'Application design',
    'Data conversion and loading',
  ]),
  single('W1-X08', 1, 'Database lifecycle', 'Monitoring performance and responding to changed requirements after commissioning belongs to:', 0, [
    'operational maintenance',
    'requirements analysis',
    'conceptual design',
    'initial data modelling only',
  ]),
  multiple('W1-X09', 1, 'Database lifecycle', 'Which concerns may be examined during database testing? Select all that apply.', [0, 1, 2, 3], [
    'Correctness and errors',
    'Performance',
    'Recoverability',
    'Security',
  ]),
  multiple('W1-X10', 1, 'RDBMS', 'Which statements about an RDBMS are correct? Select all that apply.', [0, 2, 3], [
    'It manages data represented as relations.',
    'It requires row order to carry business meaning.',
    'It supports operations that create, read, update and delete table data.',
    'It can enforce constraints derived from business rules.',
  ]),

  single('W2-X01', 2, 'Data modelling process', 'Why is data modelling described as iterative?', 0, [
    'The model is progressively revised as requirements and alternatives become clearer.',
    'Every entity must be drawn repeatedly in the final ERD.',
    'The database must contain duplicate rows.',
    'Physical storage is chosen before requirements are known.',
  ]),
  single('W2-X02', 2, 'Data models', 'What important organisational role does a data model serve?', 3, [
    'It replaces every application program.',
    'It stores the live data itself.',
    'It guarantees that all users have identical jobs.',
    'It provides a shared communication blueprint for data requirements.',
  ]),
  single('W2-X03', 2, 'Naming conventions', 'Which attribute name best follows the course conceptual-modelling convention?', 1, [
    'Customer Name',
    'CustomerName',
    'Customer-Name!',
    'customer name value',
  ]),
  single('W2-X04', 2, 'Attributes', 'What does it mean when an attribute is optional?', 2, [
    'It may contain several simultaneous values.',
    'It is not part of the model.',
    'An entity occurrence may exist without a value for that attribute.',
    'Its value is automatically calculated.',
  ]),
  single('W2-X05', 2, 'Cardinality', 'An account must have at least one and at most two cards. Which cardinality describes Cards per Account?', 0, [
    '1..2',
    '0..1',
    '0..many',
    '2..many',
  ]),
  single('W2-X06', 2, 'Foreign-key placement', 'Why is the parent key placed on the many side when mapping a regular 1:M relationship?', 3, [
    'To make every child a weak entity',
    'To remove the parent entity',
    'To turn the relationship into M:M',
    'So each many-side occurrence can reference its one-side parent',
  ]),
  single('W2-X07', 2, 'Weak entities', 'Which statement about the owner of a weak entity is correct?', 1, [
    'The owner must always be a strong entity.',
    'The owner may be strong or may itself be weak.',
    'A weak entity cannot own another weak entity.',
    'The owner never contributes to the weak entity key.',
  ]),
  single('W2-X08', 2, 'M:M resolution', 'Room and Equipment are M:M over time. AssignedEquipment records DateAssigned. Which identifiers should AssignedEquipment borrow directly?', 2, [
    'BuildingID only',
    'DateAssigned only',
    'The identifiers of Room and Equipment, plus another key component if repeated assignments require it',
    'No identifiers because associative entities have no keys',
  ]),
  multiple('W2-X09', 2, 'Noun-verb analysis', 'Which statements support noun-verb analysis of a narrative? Select all that apply.', [0, 1, 3], [
    'Important nouns may suggest entities or attributes.',
    'Verbs may suggest relationships.',
    'Every noun must become an entity.',
    'Candidate elements must still be checked against business rules.',
  ]),
  multiple('W2-X10', 2, 'ER design alternatives', 'Which choices can legitimately depend on how the organisation uses the data? Select all that apply.', [0, 1, 2], [
    'Modelling Address as an entity or as attributes',
    'Modelling a concept as an entity or a relationship',
    'Choosing a unary, binary or n-ary relationship',
    'Allowing duplicate identifiers',
  ]),

  single('W3-X01', 3, 'ERD development', 'After entities and relationships are identified, which step must occur before the ERD can be considered complete?', 2, [
    'Insert production data immediately.',
    'Choose disk file organisations first.',
    'Add attributes and identifiers, model constraints, refine weak/M:M structures and verify against business rules.',
    'Remove all relationships.',
  ]),
  single('W3-X02', 3, 'Entity selection', 'Which item should normally be ignored rather than modelled as an entity in a medical-practice database?', 1, [
    'Patient',
    'The database system as a whole',
    'Appointment',
    'Doctor',
  ]),
  single('W3-X03', 3, 'Terminology', 'Which terms all refer to one horizontal occurrence in a relation?', 0, [
    'Tuple, row and record',
    'Attribute, column and field',
    'Schema, key and domain',
    'Relation, table and database',
  ]),
  single('W3-X04', 3, 'Terminology', 'Which terms all refer to one named vertical component of a relation?', 3, [
    'Instance, row and record',
    'Tuple, relation and table',
    'Cardinality, degree and arity',
    'Attribute, column and field',
  ]),
  single('W3-X05', 3, 'Entity versus attribute', 'When is Address most strongly justified as a separate entity type?', 1, [
    'Every customer has exactly one unstructured address string and no address details are queried.',
    'Customers may have several reusable addresses with their own structured details.',
    'The address contains letters.',
    'Address is mentioned after Customer in the narrative.',
  ]),
  single('W3-X06', 3, 'Natural keys', 'During requirements modelling, why are natural keys normally preferred?', 2, [
    'They always occupy less storage than integers.',
    'They remove the need for candidate keys.',
    'They use terms recognised by the business and avoid inventing implementation details too early.',
    'They can never change.',
  ]),
  single('W3-X07', 3, 'Schema on write', 'What does “schema on write” mean in the Week 3 context?', 0, [
    'The structure and integrity constraints are known and checked when data is inserted or modified.',
    'The schema is inferred only after all data has been stored.',
    'Rows may ignore the declared attributes.',
    'The database has no legal-instance concept.',
  ]),
  single('W3-X08', 3, 'Multivalued mapping', 'A bank records exactly home, work and mobile numbers for each customer. Which logical mapping matches the lecture example?', 3, [
    'Store all three in one comma-separated cell.',
    'Delete the phone information.',
    'Use PhoneNumber as the Customer primary key.',
    'Flatten them into separate home_num, work_num and mobile attributes.',
  ]),
  single('W3-X09', 3, 'Referential actions', 'In the course examples, which action is normally appropriate when deleting an owner of identifying weak rows?', 1, [
    'SET DEFAULT to an unrelated owner',
    'CASCADE deletion to the owned weak rows',
    'Remove the foreign-key constraint first',
    'Keep ownerless weak rows',
  ]),
  multiple('W3-X10', 3, 'Conceptual-to-instance cycle', 'Which stages belong to the complete modelling-to-data cycle shown in Week 3? Select all that apply.', [0, 1, 2, 3], [
    'Conceptual design',
    'Logical and physical design',
    'Implementation',
    'Creation of a database instance',
  ]),

  single('W4-X01', 4, 'Physical design', 'Which input to physical design most directly influences indexing and record organisation decisions?', 2, [
    'The colour of the ERD',
    'The alphabetical order of entity names',
    'Response-time expectations',
    'The number of lecture slides',
  ]),
  single('W4-X02', 4, 'Binary 1:1 mapping', 'Both sides of a 1:1 relationship are optional. According to the lecture rule, where may the foreign key be placed?', 0, [
    'On either side, chosen consistently',
    'On both sides with unrelated values',
    'Only in a mandatory associative entity',
    'Nowhere',
  ]),
  single('W4-X03', 4, 'Character types', 'What happens when a value shorter than CHAR(M) is stored?', 3, [
    'It is converted to an integer.',
    'The column becomes VARCHAR automatically.',
    'The row is always rejected.',
    'The stored value is right-padded with spaces to the fixed length.',
  ]),
  single('W4-X04', 4, 'Character types', 'Which type is designed for a very large variable-length text value beyond an ordinary short VARCHAR?', 1, [
    'SMALLINT',
    'LONGTEXT',
    'DATE',
    'BIT(1)',
  ]),
  single('W4-X05', 4, 'Character types', 'Which MySQL type explicitly restricts a value to one member of a declared list?', 2, [
    'BLOB',
    'DOUBLE',
    'ENUM',
    'YEAR',
  ]),
  single('W4-X06', 4, 'Integer types', 'Which type can represent unsigned whole numbers from 0 to 255?', 0, [
    'TINYINT UNSIGNED',
    'CHAR(255)',
    'DECIMAL(2,55)',
    'TIME',
  ]),
  single('W4-X07', 4, 'Integer types', 'What is the correct interpretation of INT(M) in the course guidance?', 1, [
    'M sets the number of bytes used for the integer.',
    'Do not use M to try to specify an integer value range or digit capacity.',
    'M is the number of decimal places.',
    'INT(M) stores a variable-length string.',
  ]),
  single('W4-X08', 4, 'Boolean and bit types', 'How are Boolean values represented by MySQL in the lecture material?', 3, [
    'As DATE values',
    'As CHAR values only',
    'As a repeating group',
    'Using TINYINT-style 1 for true and 0 for false',
  ]),
  single('W4-X09', 4, 'Decimal types', 'In DECIMAL(8,2), what do 8 and 2 represent?', 0, [
    'Eight total digits of precision, including two digits after the decimal point',
    'Eight bytes and two rows',
    'Eight decimal places and two total digits',
    'Eight tables and two keys',
  ]),
  single('W4-X10', 4, 'Temporal types', 'Which type can represent either a time of day or an elapsed duration, including values longer than 24 hours?', 2, [
    'YEAR',
    'DATE',
    'TIME',
    'TIMESTAMP',
  ]),
  single('W4-X11', 4, 'Normalisation preparation', 'Which value should normally be excluded from the initial relation because it can be calculated from recorded data?', 1, [
    'ProductID',
    'InvoiceTotal calculated from line quantities and prices',
    'CustomerID',
    'InvoiceDate',
  ]),
  single('W4-X12', 4, 'Second Normal Form', 'A 1NF relation has a single-attribute primary key. What follows about 2NF?', 3, [
    'It must have a partial dependency.',
    'It cannot contain non-key attributes.',
    'It is automatically in 3NF.',
    'It is already in 2NF because no proper part of a composite key exists.',
  ]),
  single('W4-X13', 4, 'Third Normal Form', 'When removing DeptID → DeptName from Employee, what must remain in Employee?', 0, [
    'DeptID as a foreign key to Department',
    'A duplicate copy of DeptName',
    'No department reference',
    'Every Department attribute',
  ]),
  multiple('W4-X14', 4, 'Exam scope', 'Which topics are within the Week 4 normalisation examination scope? Select all that apply.', [0, 1, 2], [
    'Functional dependencies',
    'Armstrong\'s axioms',
    'UNF through 3NF',
    'BCNF through 6NF',
  ]),
  multiple('W1-X11', 1, 'Design levels', 'Which statements correctly distinguish database design levels? Select all that apply.', [0, 1, 3], [
    'Conceptual design captures high-level entities and connections and may retain M:M relationships.',
    'Logical design defines relations, columns and keys but remains independent of a specific vendor.',
    'Physical design avoids data types and indexes.',
    'Physical design implements the logical model for a particular DBMS.',
  ]),
  single('W3-X11', 3, 'Primary-key selection', 'Which candidate key is generally the strongest primary-key choice?', 2, [
    'The one with the most columns',
    'The one most likely to change',
    'A minimal, stable candidate key that uniquely identifies the occurrence',
    'Any currently duplicated descriptive attribute',
  ]),
  multiple('W4-X15', 4, 'Character types', 'Which statements about MySQL character types match the Week 4 slides? Select all that apply.', [0, 1, 3], [
    'CHAR(M) has M from 1 to 255 in the lecture material.',
    'VARCHAR(M) stores only the inserted characters rather than padding to M.',
    'TEXT values are always stored inline with the rest of the row.',
    'TEXT and BLOB have a maximum of 65,535 characters or bytes in the lecture summary.',
  ]),
  multiple('W4-X16', 4, 'Integer ranges', 'Which MySQL integer range statements are correct? Select all that apply.', [0, 1, 3], [
    'SMALLINT signed ranges from -32,768 to 32,767.',
    'SMALLINT UNSIGNED ranges from 0 to 65,535.',
    'INT UNSIGNED has a maximum of 65,535.',
    'INT signed ranges approximately from -2.1 billion to 2.1 billion.',
  ]),
  multiple('W4-X17', 4, 'Integer ranges', 'Which statements about larger integer types are correct? Select all that apply.', [0, 2, 3], [
    'MEDIUMINT UNSIGNED can store values up to 16,777,215.',
    'BIGINT stores less range than SMALLINT.',
    'BIGINT is suitable when values may exceed the INT range.',
    'UNSIGNED removes the negative range and increases the positive maximum.',
  ]),
  single('W4-X18', 4, 'Bit types', 'What does BIT(6) specify?', 1, [
    'Six decimal places',
    'Storage for a six-bit value',
    'A Boolean that must equal 6',
    'A six-character text field',
  ]),
  multiple('W4-X19', 4, 'Floating-point types', 'Which statements about FLOAT and DOUBLE match the lecture material? Select all that apply.', [0, 2, 3], [
    'FLOAT is single precision.',
    'DOUBLE is exact fixed-point storage for money.',
    'DOUBLE provides greater precision and range than FLOAT.',
    'Floating-point types are often used for scientific data.',
  ]),
  multiple('W4-X20', 4, 'Temporal ranges', 'Which statements about MySQL temporal types match the Week 4 slides? Select all that apply.', [0, 1, 3], [
    'TIMESTAMP in the lecture range ends in January 2038.',
    'YEAR covers 1901 to 2155 in the lecture summary.',
    'DATE always includes a time-zone conversion.',
    'DATETIME can store both date and time parts.',
  ]),
  single('W4-X21', 4, 'Normalisation terminology', 'In X → Y, what is X called?', 0, [
    'The determinant',
    'The repeating group',
    'The database instance',
    'The foreign relation',
  ]),
];

export const coverageShort = [
  short('W1-X01S', 1, 'Client-server', 'Describe the roles of a database server, DBMS, database client and web/application server in a client-server system.', 'The database server runs the DBMS and stores the shared database. A database client or administration tool sends database requests. A web/application server runs application logic and may act as a database client for end users.'),
  short('W1-X02S', 1, 'Database lifecycle', 'List the database development lifecycle stages shown in Week 1 in a defensible order.', 'Database planning → systems definition → requirements definition and analysis → conceptual design → logical design → physical design, alongside application design → implementation → data conversion and loading → testing → operational maintenance.'),
  short('W1-X03S', 1, 'Relational constraints', 'Give three business-rule constraints that an RDBMS could enforce for a Student database.', 'Examples: StudentID is unique and not null; StudentType is restricted to PG or UG; an enrolment must reference an offered Subject; Mark must be within its permitted domain.'),

  short('W2-X01S', 2, 'ERD method', 'Give an ordered method for building and checking a conceptual ERD from a business narrative.', 'Identify major entities; identify relationships; add attributes and identifiers; assign connectivity; assign minimum/maximum participation; identify weak entities; resolve M:M relationships; reread every rule in both directions and verify the ERD.'),
  short('W2-X02S', 2, 'Attributes', 'Classify HomeAddress(Street, Suburb, Postcode), {Qualification}, [Age] and MiddleName using the course attribute categories.', 'HomeAddress: composite. Qualification: multivalued. Age: derived. MiddleName: optional if an occurrence may have no value.'),
  short('W2-X03S', 2, 'Weak-entity chain', 'Building owns weak Room, and Room owns weak EquipmentPosition identified by PositionNo within a room. Give the conceptual identifiers.', 'Building: BuildingID. Room: (BuildingID, RoomNo). EquipmentPosition: (BuildingID, RoomNo, PositionNo). The borrowed components are PFKs in their child relations.'),

  short('W3-X01S', 3, 'Terminology', 'Match relation, attribute and tuple to the common MySQL and MS Access terms.', 'Relation = table. Attribute = MySQL column or Access field. Tuple = MySQL row or Access record.'),
  short('W3-X02S', 3, 'Entity selection', 'From “A medical practice records patients, doctors and appointments; receptionists enter data and print schedules,” state what should and should not be entities.', 'Likely entities: Patient, Doctor and Appointment. The practice system as a whole, the receptionist as merely a system user, and the printed schedule as an output are not automatically entities.'),
  short('W3-X03S', 3, 'Implementation constraints', 'Write the essential constraint clauses for Order(OrderID, CustomerID), where every order must reference a customer and customer deletion is blocked while orders exist.', 'PRIMARY KEY (OrderID); CustomerID NOT NULL; FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID) ON DELETE NO ACTION.'),

  short('W4-X01S', 4, 'Physical design', 'List four kinds of input and four kinds of decision involved in physical database design.', 'Inputs include normalised relations, attribute definitions, response-time expectations, security, backup/recovery, integrity expectations and DBMS technology. Decisions include data types, physical record descriptions, file organisation, indexes, database architecture and query optimisation.'),
  short('W4-X02S', 4, 'Data types', 'Choose types for a fixed two-letter state code, a long biography, an unsigned count up to 255, an exact price and a Boolean flag.', 'State code: CHAR(2). Biography: TEXT or LONGTEXT as required. Count: TINYINT UNSIGNED. Price: DECIMAL(p,s). Boolean: TINYINT/BOOLEAN represented as 1 or 0.'),
  short('W4-X03S', 4, 'Functional dependencies', 'For R(A, B, C, D) with A → B and B → C, state the determinant in each dependency and one dependency inferred by transitivity.', 'A is the determinant of A → B. B is the determinant of B → C. By transitivity, A → C.'),
  short('W4-X04S', 4, 'Normalisation', 'State the test for 1NF, 2NF and 3NF in one line each.', '1NF: atomic single values and no repeating groups. 2NF: 1NF plus no non-key attribute partially depends on part of a composite candidate key. 3NF: 2NF plus no transitive dependency of a non-key attribute on a candidate key through another non-key attribute.'),
  short('W4-X05S', 4, 'Normalisation case', 'Normalise Agent(AgentID, AgentName, Mobile, (PropertyID, PropertyAddress, OwnerID, OwnerName, OwnerMobile, SaleDate, SaleAmount)) to 3NF.', 'Agent(AgentID, AgentName, Mobile); Property(PropertyID, PropertyAddress); Owner(OwnerID, OwnerName, OwnerMobile); PropertySale(PropertyID, OwnerID, SaleDate, SaleAmount, AgentID), with the identifiers referenced as foreign keys.'),
  short('W4-X06S', 4, 'Integer types', 'Choose the smallest suitable MySQL integer type for an unsigned value whose maximum is 50,000, and state why.', 'SMALLINT UNSIGNED, because its range is 0 to 65,535, which includes 50,000 while using a smaller range than MEDIUMINT or INT.'),
];
