import { multiple, short, single } from './quiz-types';

export const week4Choice = [
  single('W4-C01', 4, 'Binary 1:1 mapping', 'Citizen has an optional Passport, and each Passport must belong to exactly one Citizen. In a 1:1 mapping, where is CitizenID most naturally placed?', 1, [
    'As a nullable FK in Citizen',
    'As a non-null, unique FK in Passport',
    'In a mandatory associative relation in every design',
    'Nowhere, because 1:1 relationships need no foreign key',
  ]),
  single('W4-C02', 4, 'Binary 1:M mapping', 'Each Course offers many Classes; each Class belongs to one Course. Which mapping is correct?', 3, [
    'Put ClassID as a foreign key in Course.',
    'Merge every class into the Course primary key.',
    'Create an associative relation because every 1:M is M:M.',
    'Put CourseID as a foreign key in Class.',
  ]),
  single('W4-C03', 4, 'Binary M:M mapping', 'What is required when mapping Student M:M Club?', 0, [
    'An associative relation containing foreign keys to Student and Club',
    'A single ClubID column in Student',
    'A single StudentID column in Club',
    'No new relation if both entities already have keys',
  ]),
  single('W4-C04', 4, 'Identifying relationships', 'Room is weak and identified by (BuildingID, RoomNumber). How is BuildingID classified in Room?', 2, [
    'A non-key descriptive attribute only',
    'A primary key but never a foreign key',
    'A primary-foreign key (PFK)',
    'A derived attribute',
  ]),
  single('W4-C05', 4, 'Unary 1:1 relationships', 'Each employee may mentor at most one employee, and each employee may have at most one mentor. Which relational mapping is suitable?', 1, [
    'A repeating list of mentee IDs inside Employee',
    'A nullable MentorID self-FK in Employee with a uniqueness constraint',
    'A non-null ManagerID with no FK constraint',
    'Delete EmployeeID and use MentorID as the only key',
  ]),
  single('W4-C06', 4, 'Unary 1:M relationships', 'An employee may manage many employees; each employee has at most one manager. Which mapping is usual?', 3, [
    'ManagerID is stored once in a separate Manager table with no employee reference.',
    'EmployeeID becomes a multivalued attribute.',
    'Each manager row stores a comma-separated list of staff.',
    'Employee contains a nullable ManagerID foreign key referencing Employee.EmployeeID.',
  ]),
  single('W4-C07', 4, 'Unary M:M relationships', 'A Component may contain many Components and may be used inside many Components. What mapping is appropriate?', 0, [
    'ComponentComposition(ParentComponentID, ChildComponentID, Quantity), with two role-distinct self-referencing FKs',
    'One ParentComponentID column in Component only',
    'One ChildComponentID column in Component only',
    'A derived text description with no keys',
  ]),
  single('W4-C08', 4, 'MySQL character types', 'Which type is normally preferred for names whose lengths vary substantially?', 2, [
    'CHAR(255)',
    'BINARY(255)',
    'VARCHAR with a suitable maximum length',
    'DECIMAL',
  ]),
  single('W4-C09', 4, 'MySQL character types', 'Which value is the best candidate for CHAR rather than VARCHAR?', 1, [
    'A free-form product description',
    'A fixed two-letter Australian state code',
    'A customer street address',
    'A variable-length email address',
  ]),
  single('W4-C10', 4, 'Identifier data types', 'A membership number may contain leading zeros and is never used arithmetically. Which storage choice is safest?', 3, [
    'FLOAT',
    'DECIMAL with two fractional digits',
    'DATE',
    'A character type of suitable length',
  ]),
  single('W4-C11', 4, 'Exact numeric types', 'Which MySQL type is most appropriate for a monetary value requiring exact decimal arithmetic?', 0, [
    'DECIMAL(p,s)',
    'FLOAT',
    'TEXT',
    'TIMESTAMP',
  ]),
  single('W4-C12', 4, 'Approximate numeric types', 'Which statement about FLOAT and DOUBLE is most accurate?', 2, [
    'They guarantee exact decimal representation for money.',
    'They are character types for numeric-looking identifiers.',
    'They store approximate numeric values and may introduce rounding effects.',
    'They store only whole numbers.',
  ]),
  single('W4-C13', 4, 'Temporal types', 'Which type best stores a calendar date when no time of day is needed?', 1, [
    'TIME',
    'DATE',
    'DATETIME',
    'VARCHAR by default',
  ]),
  single('W4-C14', 4, 'Temporal types', 'Which type is most direct for a future appointment date and time when automatic timezone conversion is not required?', 3, [
    'YEAR',
    'DATE only',
    'CHAR',
    'DATETIME',
  ]),
  single('W4-C15', 4, 'Temporal types', 'Which statement best distinguishes MySQL TIMESTAMP from DATETIME?', 0, [
    'TIMESTAMP commonly supports UTC-based conversion by the session time zone, whereas DATETIME stores the stated date-time value without that conversion.',
    'DATETIME stores only dates, whereas TIMESTAMP stores only times.',
    'TIMESTAMP is always a character string.',
    'DATETIME cannot represent a time of day.',
  ]),
  single('W4-C16', 4, 'Anomalies', 'One product is stored on several invoice rows. Changing its description requires changing every occurrence. What anomaly is this?', 1, [
    'Insertion anomaly',
    'Update anomaly',
    'Deletion anomaly',
    'Referential action',
  ]),
  single('W4-C17', 4, 'Anomalies', 'A supplier cannot be recorded until it supplies at least one product because supplier and product facts share one table. What anomaly is this?', 2, [
    'Update anomaly',
    'Deletion anomaly',
    'Insertion anomaly',
    'Cardinality anomaly',
  ]),
  single('W4-C18', 4, 'Anomalies', 'Deleting the only course enrolment also removes the only stored details about the course. What anomaly is this?', 3, [
    'Domain anomaly',
    'Insertion anomaly',
    'Update anomaly',
    'Deletion anomaly',
  ]),
  single('W4-C19', 4, 'Functional dependencies', 'What does X → Y mean?', 1, [
    'Y determines X in every possible instance.',
    'For any legal relation instance, equal X values imply equal Y values.',
    'X and Y must both be foreign keys.',
    'Every Y value must be different.',
  ]),
  single('W4-C20', 4, 'Normal forms', 'Which requirement is central to First Normal Form (1NF)?', 0, [
    'Every attribute position contains a single atomic value, with no repeating groups.',
    'Every determinant is a candidate key.',
    'No non-key attribute depends on another non-key attribute.',
    'Every relation has a single-attribute primary key.',
  ]),
  multiple('W4-C21', 4, 'Data types', 'Which data-type choices are appropriate? Select all that apply.', [0, 1, 3], [
    'DECIMAL(10,2) for exact prices',
    'CHAR(3) for a fixed three-letter airport code',
    'FLOAT for an identifier that must preserve leading zeros',
    'DATE for a birth date when time is irrelevant',
  ]),
  multiple('W4-C22', 4, 'Unary mapping', 'Which statements about unary relationships are correct? Select all that apply.', [0, 2, 3], [
    'A unary 1:M relationship can use a self-referencing foreign key.',
    'A unary M:M relationship needs only one self-FK in the original relation.',
    'A unary M:M associative relation uses two foreign keys with different role names.',
    'Role names help distinguish how the same entity type participates.',
  ]),
  multiple('W4-C23', 4, 'Anomalies', 'Which situations indicate modification anomalies? Select all that apply.', [0, 1, 2], [
    'The same fact must be updated in several rows.',
    'A fact cannot be inserted without an unrelated fact.',
    'Deleting one row unintentionally removes the only record of another fact.',
    'A primary key uniquely identifies each row.',
  ]),
  multiple('W4-C24', 4, 'Functional dependencies', 'Given StudentID → StudentName and SubjectID → SubjectName, which dependencies follow by Armstrong\'s axioms? Select all that apply.', [0, 1, 3], [
    'StudentID → StudentName',
    '(StudentID, SubjectID) → StudentName',
    'StudentName → StudentID',
    '(StudentID, SubjectID) → (StudentName, SubjectName)',
  ]),
  multiple('W4-C25', 4, 'Armstrong axioms', 'Which are Armstrong\'s basic inference axioms? Select all that apply.', [0, 1, 2], [
    'Reflexivity',
    'Augmentation',
    'Transitivity',
    'Referential integrity',
  ]),
  multiple('W4-C26', 4, 'Normalisation process', 'Which statements about normalisation are correct? Select all that apply.', [0, 1, 3], [
    '1NF removes repeating groups and requires atomic values.',
    '2NF removes partial dependencies of non-key attributes on part of a composite candidate key.',
    '3NF requires every relation to have a single-column key.',
    '3NF removes transitive dependencies of non-key attributes on candidate keys.',
  ]),
  multiple('W4-C27', 4, 'Second Normal Form', 'Enrolment(StudentID, SubjectID, StudentName, SubjectName, Mark) has key (StudentID, SubjectID). Which dependencies violate 2NF? Select all that apply.', [0, 1], [
    'StudentID → StudentName',
    'SubjectID → SubjectName',
    '(StudentID, SubjectID) → Mark',
    '(StudentID, SubjectID) → StudentID',
  ]),
  multiple('W4-C28', 4, 'Third Normal Form', 'Employee(EmployeeID, DeptID, DeptName, EmployeeName) has EmployeeID → DeptID and DeptID → DeptName. Which statements are correct? Select all that apply.', [0, 2, 3], [
    'DeptName is transitively dependent on EmployeeID.',
    'DeptName must remain in Employee to reach 3NF.',
    'Create Department(DeptID, DeptName).',
    'Keep DeptID in Employee as a foreign key.',
  ]),
  multiple('W4-C29', 4, 'Normalisation case', 'InvoiceLine(InvoiceID, ProductID, InvoiceDate, ProductName, Quantity) has key (InvoiceID, ProductID), InvoiceID → InvoiceDate and ProductID → ProductName. Which decompositions support 2NF? Select all that apply.', [0, 1, 2], [
    'Invoice(InvoiceID, InvoiceDate)',
    'Product(ProductID, ProductName)',
    'InvoiceLine(InvoiceID, ProductID, Quantity)',
    'One unchanged InvoiceLine relation containing all attributes',
  ]),
];

export const week4Short = [
  short('W4-S01', 4, 'Binary 1:1 mapping', 'Each nurse may manage at most one care centre; each care centre must have exactly one nurse manager. Give a suitable relational mapping.', 'Place ManagerNurseID in CareCentre as a NOT NULL, UNIQUE foreign key referencing Nurse(NurseID).'),
  short('W4-S02', 4, 'Unary 1:M mapping', 'An employee may manage many employees and each employee has at most one manager. Give the relation-level mapping.', 'Employee(EmployeeID PK, …, ManagerID FK NULL → Employee.EmployeeID). ManagerID is nullable for employees with no manager.'),
  short('W4-S03', 4, 'Unary M:M mapping', 'An item may contain many component items and may itself be used in many items. Quantity is recorded. Give the mapping.', 'ItemComponent(ParentItemID PK/FK → Item.ItemID, ChildItemID PK/FK → Item.ItemID, Quantity), with composite PK (ParentItemID, ChildItemID).'),
  short('W4-S04', 4, 'MySQL data types', 'Choose suitable MySQL types for ProductCode ABC-0042, ProductName, UnitPrice and QuantityInStock.', 'ProductCode: CHAR or VARCHAR of suitable length; ProductName: VARCHAR; UnitPrice: DECIMAL(p,2); QuantityInStock: a suitable integer type.'),
  short('W4-S05', 4, 'Temporal types', 'Choose suitable MySQL types for DateOfBirth and a scheduled appointment date-time.', 'DateOfBirth: DATE. Scheduled appointment: DATETIME when the stated local date-time should be stored without automatic timezone conversion.'),
  short('W4-S06', 4, 'Anomalies', 'Give one concise example each of an insertion, update and deletion anomaly.', 'Insertion: cannot store a supplier until a product exists. Update: a supplier address must be changed in many rows. Deletion: deleting the last product row removes the only supplier details.'),
  short('W4-S07', 4, 'Functional dependencies', 'Define a functional dependency and list Armstrong\'s three basic axioms.', 'X → Y means equal X values imply equal Y values in every legal instance. The axioms are reflexivity, augmentation and transitivity.'),
  short('W4-S08', 4, 'UNF to 1NF', 'InvoiceUNF(InvoiceID, InvoiceDate, {ProductID, ProductName, Quantity}) contains a repeating product group. Show a 1NF structure.', 'Invoice1NF(InvoiceID, InvoiceDate, ProductID, ProductName, Quantity), one row per invoice-product occurrence, with composite key (InvoiceID, ProductID).'),
  short('W4-S09', 4, '1NF to 2NF', 'Normalise Invoice1NF(InvoiceID, ProductID, InvoiceDate, ProductName, Quantity), key (InvoiceID, ProductID), given InvoiceID → InvoiceDate and ProductID → ProductName, to 2NF.', 'Invoice(InvoiceID, InvoiceDate); Product(ProductID, ProductName); InvoiceLine(InvoiceID, ProductID, Quantity).'),
  short('W4-S10', 4, '2NF to 3NF', 'Employee(EmployeeID, EmployeeName, DeptID, DeptName), key EmployeeID, has DeptID → DeptName. Decompose to 3NF.', 'Employee(EmployeeID, EmployeeName, DeptID) and Department(DeptID, DeptName), with Employee.DeptID an FK to Department.'),
];
